[versions]
androidGradlePlugin = "8.2.1"
androidxActivity = "1.9.0-alpha01"
androidxAnnotations = "1.8.2"
androidxBenchmark = "1.2.2"
androidxCore = "1.13.0-alpha03"
androidxDatastore = "1.1.0-beta01"
androidxLifecycle = "2.7.0"
androidxNavigation = "2.7.6"
androidxPaging = "3.3.0-alpha02"
androidxSplashscreen = "1.1.0-alpha02"
androidxStartup = "1.2.0-alpha02"
androidxTestCore = "1.6.0-alpha04"
androidxTestJunit = "1.2.0-alpha02"
androidxTestRules = "1.6.0-alpha02"
androidxTestRunner = "1.6.0-alpha05"
androidxTestUiAutomator = "2.3.0-beta01"
androidxTracing = "1.3.0-alpha02"
baselineProfilePlugin = "1.2.2"
coil = "2.5.0"
commonmark = "0.21.0"
composeBom = "2024.01.00-alpha01"
composeCompiler = "1.5.8"
desugar = "2.0.4"
detekt = "1.23.4"
detektCompose = "0.3.10"
espresso = "3.6.0-alpha02"
hilt = "2.50"
hiltNavigation = "1.2.0-alpha01"
kotlin = "1.9.22"
kotlinxCollections = "0.3.7"
kotlinxCoroutines= "1.7.3"
kotlinxDatetime = "0.5.0"
kotlinxSerialization = "1.6.2"
ksp = "1.9.22-1.0.17"
leakCanary = "2.13"
materialLegacy = "1.11.0"
okhttp = "5.0.0-alpha.12"
profileinstallerVersion = "1.3.1"
retrofit = "2.9.0"
retrofitKotlinx = "1.0.0"
timber = "5.0.1"

[libraries]
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity"}
androidx-annotations = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotations"}
androidx-benchmark-micro = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "androidxBenchmark"}
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxBenchmark"}
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore"}
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastore"}
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle"}
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle"}
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation"}
androidx-navigation-test = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation"}
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPaging"}
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "androidxPaging"}
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "androidxPaging"}
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplashscreen"}
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup"}
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore"}
androidx-test-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestJunit"}
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules"}
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner"}
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxTestUiAutomator"}
androidx-tracing = { module = "androidx.tracing:tracing", version.ref = "androidxTracing"}
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil"}
commonmark = { module = "org.commonmark:commonmark", version.ref = "commonmark"}
compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "composeBom"}
compose-material = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-testing = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-testing-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar"}
detekt-rules-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose"}
detekt-rules-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt"}
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso"}
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation"}
hilt-core = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt"}
kotlinx-collections = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollections"}
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines"}
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines"}
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime"}
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization"}
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary"}
material-legacy = { module = "com.google.android.material:material", version.ref = "materialLegacy"}
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstallerVersion" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlinx = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinx" }
retrofit-mock = { group = "com.squareup.retrofit2", name = "retrofit-mock", version.ref = "retrofit" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-app = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baseline-profile = { id = "androidx.baselineprofile", version.ref = "baselineProfilePlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
